name: 'mt-build'
description: 'description would be nice'

inputs: 
  platform:
    description: 'the target platform'
    required: true
    default: 'mac'

runs: 
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.platform }}